STUBS_DEFAULT_PATH = 'stubs'
PLAYER_DETECTOR_PATH = 'models/lastVersionModel.pt'
BALL_DETECTOR_PATH = 'models/lastVersionModel.pt'
COURT_KEYPOINT_DETECTOR_PATH = 'models/court_keypoint_detector_model_v3.pt'
OUTPUT_VIDEO_PATH = 'output_videos/output_video.avi'